from enum import Enum


class ClientMessageType(str, Enum):
    GET_SESSION_METADATA = "GET_SESSION_METADATA"
    GET_MOVE_LIST = "GET_MOVE_LIST"
    GET_DETAILED_ANALYSIS = "GET_DETAILED_ANALYSIS"
    GET_TRACE_TREE = "GET_TRACE_TREE"
    GET_GAME_ANALYSIS = "GET_GAME_ANALYSIS"
    SET_MODEL_PARAMS = "SET_MODEL_PARAMS"


class ServerMessageType(str, Enum):
    ERROR = "ERROR"
    SESSION_METADATA = "SESSION_METADATA"
    MOVE_LIST = "MOVE_LIST"
    ANALYSIS_UPDATE = "ANALYSIS_UPDATE"
    TRACE_TREE_NODE = "TRACE_TREE_NODE"
    TRACE_TREE_NODE_BATCH = "TRACE_TREE_NODE_BATCH"
    ANALYSIS_PROGRESS = "ANALYSIS_PROGRESS"
    FULL_ANALYSIS_COMPLETE = "FULL_ANALYSIS_COMPLETE"
    COMMENT_UPDATE = "COMMENT_UPDATE"
    COMMENT_HISTORY = "COMMENT_HISTORY"
    AI_COMMENT_UPDATE = "AI_COMMENT_UPDATE"
    AI_GENERATION_STATUS = "AI_GENERATION_STATUS"
    MODEL_PARAMS_UPDATED = "MODEL_PARAMS_UPDATED"
